import type { ArchEdge, ArchNode } from "./types";

// Clickable system map. Coordinates in a 100×100 layout grid.

export const ARCH_NODES: ArchNode[] = [
  {
    id: "er4u",
    label: "Billing Software (er4u)",
    sublabel: "no API — manual CSV/XLS exports",
    x: 2, y: 2, w: 22, h: 12, tone: "external",
    purpose: "The system of record for sales/purchases — and the constraint that shaped everything: no API, only manual exports.",
    responsibilities: ["Prints bills, records purchases", "Exports 6 report types on demand", "Playwright automation (er4u_export.py) fetches sales files"],
    whyThisDesign: "Not a choice — a constraint. The entire raw-first architecture exists because this source is unreliable and uncontrollable.",
    alternatives: "A billing system with an API/webhooks would enable streaming ingestion — and remove the project's most interesting constraint.",
    tradeoffs: "Batch freshness (daily at best) is the ceiling on every downstream 'real-time' ambition. Designs honest to that ceiling stay simple.",
    interview: ["How do you build reliable analytics on an unreliable, API-less source?"],
    files: [{ path: "scripts/er4u_export.py", note: "Playwright export automation" }],
    relatedTopics: ["three-layer-architecture"],
    myConfidence: "none",
  },
  {
    id: "ingestion",
    label: "Ingestion Layer",
    sublabel: "header maps → chunked insert → batch audit",
    x: 2, y: 18, w: 22, h: 12, tone: "data",
    purpose: "Move files into raw.* verbatim, idempotently, with full lineage — and do NOTHING else.",
    responsibilities: ["SHA-256 file dedup", "Column mapping per report type", "2000-row chunked inserts", "ingestion_batches audit rows"],
    whyThisDesign: "Ingestion is kept dumb on purpose: interpretation (dates, mobiles) lives in re-runnable derived SQL. A parsing bug in ingestion would poison raw permanently.",
    alternatives: "Parse-on-ingest (cleaner rows, unrecoverable bugs); streaming CDC (needs an API that doesn't exist).",
    tradeoffs: "Raw stores ugly text (broken date formats and all) — the cost of guaranteed recoverability.",
    interview: ["Why does your ingestion do no data cleaning?"],
    files: [{ path: "raw_ingestion/common/ingest_core.py", note: "core (stable, do-not-modify)" }],
    relatedTopics: ["idempotent-rebuilds", "three-layer-architecture"],
    myConfidence: "partial",
  },
  {
    id: "raw",
    label: "raw.* schema",
    sublabel: "append-only truth · batch lineage",
    x: 2, y: 34, w: 22, h: 12, tone: "data",
    purpose: "Immutable source of truth. Every row traceable to a file and batch. Never UPDATE, never DELETE.",
    responsibilities: ["6 report tables + ingestion_batches", "Dedup triggers", "import_batch_id + source_file_name on every row"],
    whyThisDesign: "Immutability makes every downstream bug recoverable: derived is re-derivable, so raw is the only thing that must never be wrong — and 'never wrong' is achievable only by 'never touched'.",
    alternatives: "Mutable staging tables (industry default, loses audit); event log in Kafka (same idea, infrastructure the scale doesn't justify).",
    tradeoffs: "Storage grows forever (fine — text compresses); queries against raw are ugly (fine — humans query derived).",
    interview: ["What's your recovery story when analytics code has a bug?"],
    files: [{ path: "sql/raw_tables.sql", note: "schema" }, { path: "scripts/setup_raw_triggers.py", note: "dedup triggers" }],
    relatedTopics: ["three-layer-architecture", "idempotent-rebuilds"],
    myConfidence: "solid",
  },
  {
    id: "pipeline",
    label: "Rebuild Pipeline",
    sublabel: "11 ordered SQL steps · truncate + rebuild",
    x: 27, y: 26, w: 22, h: 12, tone: "data",
    purpose: "Deterministically derive all analytics from raw: derived = f(raw), executed as ordered SQL files.",
    responsibilities: ["TRUNCATE + rebuild each derived table", "Enforce step order (00 anchors 01's date spine)", "Excel exports", "Batch-scores ML predictions"],
    whyThisDesign: "Pure-function rebuilds give idempotency by construction — no incremental merge logic, no drift, any SQL fix heals all history.",
    alternatives: "dbt (same philosophy, more tooling — the migration is straightforward later); incremental models (needed only at ~50x current scale).",
    tradeoffs: "Rebuild window = stale/empty reads mid-run; O(history) cost per run; both acceptable at weekly cadence, both have known fixes (shadow tables, incremental).",
    interview: ["Walk me through what happens when the pipeline crashes at step 4."],
    files: [{ path: "pipelines/weekly_pipeline.py", note: "orchestrator" }, { path: "sql/rebuild_derived/", note: "steps 00–10" }],
    relatedTopics: ["idempotent-rebuilds", "sql-window-functions"],
    myConfidence: "solid",
  },
  {
    id: "derived",
    label: "derived.* schema",
    sublabel: "2.3M-row time series · signals · associations",
    x: 27, y: 42, w: 22, h: 12, tone: "data",
    purpose: "Rebuildable analytics: dense product-day series, lag/rolling features, health signals, pseudo-stock, associations, customer metrics.",
    responsibilities: ["Materialized (TABLE not VIEW — the 12x lesson)", "Feature store for ML", "Every dashboard read"],
    whyThisDesign: "Materializing at rebuild time moves compute off the request path — reads are plain indexed tables. The pipeline makes materialization free.",
    alternatives: "Views (recompute per read — the 700ms mistake), materialized views (a second refresh lifecycle for nothing).",
    tradeoffs: "Staleness between rebuilds — bounded and honest; the Refresh button exists for impatience.",
    interview: ["Why TABLE instead of VIEW or MATERIALIZED VIEW for heavy dimensions?"],
    files: [{ path: "sql/derived_tables.sql", note: "schema" }, { path: "sql/rebuild_derived/05_necessary_views.sql", note: "view→table conversion" }],
    relatedTopics: ["postgres-optimization", "sql-window-functions"],
    myConfidence: "solid",
  },
  {
    id: "app-schema",
    label: "app.* schema",
    sublabel: "human-authored · Alembic-managed",
    x: 27, y: 58, w: 22, h: 12, tone: "backend",
    purpose: "State that can't be recomputed: users, canonical names, aliases, cash counts, campaigns, BOMs.",
    responsibilities: ["Survives every rebuild", "Migration-managed evolution", "Enriches derived via COALESCE joins by business key"],
    whyThisDesign: "Human judgment is the one input that isn't in raw — so it gets its own durability domain with schema migrations, joined (never copied) into analytics.",
    alternatives: "Writing human edits into derived (destroyed weekly — the trap this schema exists to avoid).",
    tradeoffs: "Read paths carry COALESCE joins everywhere — small, uniform tax for rebuild-safety.",
    interview: ["How do human edits survive a full analytics rebuild?"],
    files: [{ path: "api/migrations/versions/", note: "12 migrations" }],
    relatedTopics: ["three-layer-architecture"],
    myConfidence: "solid",
  },
  {
    id: "fastapi",
    label: "FastAPI Backend",
    sublabel: "routers · tool plugins · dependencies",
    x: 52, y: 26, w: 22, h: 12, tone: "backend",
    purpose: "The API boundary: auth, analytics reads, app writes, tool plugins, AI endpoints.",
    responsibilities: ["Core routers (auth/analytics/customers/products/suppliers/pipeline)", "Auto-discovered tool plugins ×5", "DI: get_db (ORM, app.*) vs get_conn (raw SQL, derived/raw)", "JWT guards per route"],
    whyThisDesign: "The two-dependency split encodes the data architecture in handler signatures; the plugin registry keeps main.py closed to feature growth.",
    alternatives: "Django (batteries, less async-native), Node/Express (loses the Python data ecosystem shared with the pipeline).",
    tradeoffs: "Sync DB stack (psycopg2) — simple and sufficient; async migration is a known lever if concurrency ever demands it.",
    interview: ["Why two database dependency types?", "How does a new staff tool get mounted without editing main.py?"],
    files: [{ path: "api/main.py", note: "app assembly" }, { path: "api/dependencies.py", note: "the DI seam" }, { path: "api/tools/__init__.py", note: "plugin registry" }],
    relatedTopics: ["dependency-injection", "plugin-architecture", "jwt-auth", "rbac"],
    myConfidence: "solid",
  },
  {
    id: "ai-layer",
    label: "AI Layer",
    sublabel: "provider port · tool loop · cost meter",
    x: 52, y: 42, w: 22, h: 12, tone: "ai",
    purpose: "One neutral gateway for all LLM work: providers, tools, allowlist, cost — features never touch vendor SDKs.",
    responsibilities: ["AIProvider port + Anthropic/OpenAI/OpenRouter adapters", "ChatSession tool loop (10-round cap, forced first call, errors-as-data)", "Model allowlist", "Per-turn cost accounting"],
    whyThisDesign: "A hand-built miniature of the 'LLM gateway' platform teams construct: swap vendors by config, govern models and spend at one chokepoint, own the loop you must debug.",
    alternatives: "LangChain et al. (faster start, opaque internals — wrong trade for a learning-first project), per-feature SDK calls (the sprawl this layer prevents).",
    tradeoffs: "You maintain adapters as vendors evolve; the port must grow capabilities (streaming, structured modes) deliberately, not leak them.",
    interview: ["Walk me through your agent loop.", "How would you add a fourth provider?"],
    files: [{ path: "api/ai/provider.py", note: "the port" }, { path: "api/ai/chat.py", note: "the loop" }, { path: "api/ai/cost.py", note: "the meter" }],
    relatedTopics: ["provider-abstraction", "tool-calling", "structured-outputs", "cost-tracking"],
    myConfidence: "partial",
  },
  {
    id: "llm-providers",
    label: "LLM Providers",
    sublabel: "Anthropic · OpenAI · OpenRouter",
    x: 77, y: 42, w: 21, h: 12, tone: "external",
    purpose: "External model vendors behind the port.",
    responsibilities: ["Chat + tool-use APIs", "Token usage reporting"],
    whyThisDesign: "Multi-vendor by design: price/quality/availability shift monthly; the port makes that churn a config concern.",
    alternatives: "Single-vendor commitment (simpler, hostage to pricing), self-hosted models (ops cost unjustifiable at this scale).",
    tradeoffs: "External dependency: latency, outages, price changes — mitigated by swap-ability, never eliminated.",
    interview: ["What breaks when your LLM vendor has an outage, and what's your fallback story?"],
    files: [{ path: "api/ai/providers/", note: "adapters" }],
    relatedTopics: ["provider-abstraction"],
    myConfidence: "partial",
  },
  {
    id: "ml-stack",
    label: "ML Stack",
    sublabel: "MLflow · XGBoost · batch scoring",
    x: 52, y: 58, w: 22, h: 12, tone: "ml",
    purpose: "Demand forecasting lifecycle: tracked experiments → promoted artifact → batch predictions as derived rows.",
    responsibilities: ["Notebooks 01–04 (baseline→eval)", "MLflow tracking (port 5001)", "train.py/predict.py", "derived.demand_predictions"],
    whyThisDesign: "Batch scoring over serving: consumers need daily numbers, the pipeline runs daily-ish — predictions-as-rows means no model server, trivial rollback.",
    alternatives: "Online serving endpoint (latency SLOs, infra — buys nothing here), SQL WMA forever (the baseline it had to beat, with receipts).",
    tradeoffs: "Predictions age between runs; acceptable by explicit freshness-tolerance argument.",
    interview: ["Batch vs online scoring — how did you decide?"],
    files: [{ path: "ml/", note: "notebooks + train/predict" }],
    relatedTopics: ["demand-forecasting", "mlflow-tracking"],
    myConfidence: "none",
  },
  {
    id: "storage",
    label: "Object Storage",
    sublabel: "StorageClient → Local / R2 (S3-compatible)",
    x: 77, y: 58, w: 21, h: 12, tone: "backend",
    purpose: "Images and assets: bytes in object storage, URLs in Postgres.",
    responsibilities: ["upload/delete/public_url port", "Local adapter (dev, StaticFiles)", "R2 adapter (boto3, any S3-compatible)"],
    whyThisDesign: "S3 API as the industry storage port — provider swap is env vars. Binary never enters Postgres.",
    alternatives: "BLOBs in DB (backup bloat, no CDN), vendor SDK direct (lock-in the abstraction exists to prevent).",
    tradeoffs: "Two stores to keep consistent (URL rows vs objects) — orphan cleanup is a known chore.",
    interview: ["Why never store images in the database?"],
    files: [{ path: "api/storage/client.py", note: "port + both adapters" }],
    relatedTopics: ["provider-abstraction"],
    myConfidence: "solid",
  },
  {
    id: "item-cleanup",
    label: "Item Master Cleanup",
    sublabel: "immutable runs · decision reuse · validated XLSX",
    x: 27, y: 74, w: 22, h: 14, tone: "backend",
    purpose: "Turn a fresh ER4U Item Combination Master into a minimal human review queue and a fidelity-validated workbook without granting heuristics or LLMs authority over business fields.",
    responsibilities: [
      "Validate workbook identity and protected fields",
      "Build purchase/classification/Brand/Size/Name evidence",
      "Reuse exact-baseline historical decisions conservatively",
      "Run deterministic standards and advisory semantic funnels",
      "Persist Accept/Reject/Edit audit history and generate approved copies",
    ],
    whyThisDesign: "Each upload is an audit boundary; global rules rerun, but item-specific judgment is reused only while identity and evidence baselines remain exact. This buys incremental monthly review without turning yesterday's answer into an unsafe global rule.",
    alternatives: "Mutate the source workbook in place (no recovery), re-review all 13,507 rows monthly (wasted attention), or auto-apply HIGH-confidence model output (confidence mistaken for authority).",
    tradeoffs: "Conservative invalidation creates extra review when evidence changes, and synchronous semantic analysis can make upload requests long-running. Both are accepted in favor of correctness; checkpointed background execution is the next operational improvement.",
    interview: [
      "How do you reuse human decisions without applying stale corrections?",
      "Where is the authority boundary between deterministic rules, semantic suggestions, and export values?",
    ],
    files: [
      { path: "api/tools/item_combination_cleanup/workflow.py", note: "orchestration + reuse" },
      { path: "api/tools/item_combination_cleanup/service.py", note: "review + export" },
      { path: "docs/decisions/007-item-master-cleanup-reuse.md", note: "decision record" },
    ],
    relatedTopics: ["idempotent-rebuilds", "structured-outputs", "llm-evals"],
    myConfidence: "partial",
  },
  {
    id: "nextjs",
    label: "Next.js Dashboard",
    sublabel: "internal tools · charts · this Academy",
    x: 52, y: 6, w: 22, h: 14, tone: "backend",
    purpose: "The staff-facing surface: KPIs, health tables, customers, tool UIs, campaign editor — and the Academy you're reading.",
    responsibilities: ["JWT client auth + protected layout", "Recharts visualizations", "Tool UIs driven by the manifest endpoint", "Tailscale-served for mobile"],
    whyThisDesign: "One internal app, role-gated, manifest-driven sidebar — the frontend discovers backend tools rather than hardcoding them.",
    alternatives: "Streamlit (faster, ceiling too low for the campaign editor), server-rendered templates (loses the interactive editor entirely).",
    tradeoffs: "SPA auth in localStorage (LAN-appropriate, documented), API base URL must stay relative for tailnet/mobile clients.",
    interview: ["How does the frontend know which tools exist?"],
    files: [{ path: "web/app/(internal)/", note: "routes" }, { path: "web/components/shared/Sidebar.tsx", note: "manifest-aware nav" }],
    relatedTopics: ["plugin-architecture", "jwt-auth"],
    myConfidence: "partial",
  },
];

export const ARCH_EDGES: ArchEdge[] = [
  { from: "er4u", to: "ingestion", label: "CSV/XLS" },
  { from: "ingestion", to: "raw" },
  { from: "raw", to: "pipeline", label: "read" },
  { from: "pipeline", to: "derived", label: "truncate+rebuild" },
  { from: "derived", to: "fastapi", label: "get_conn reads" },
  { from: "app-schema", to: "fastapi", label: "get_db writes" },
  { from: "derived", to: "app-schema", label: "COALESCE join" },
  { from: "fastapi", to: "nextjs", label: "JSON + JWT" },
  { from: "ai-layer", to: "fastapi" },
  { from: "ai-layer", to: "llm-providers", label: "adapters" },
  { from: "ml-stack", to: "pipeline", label: "batch predictions" },
  { from: "storage", to: "fastapi", label: "asset URLs" },
  { from: "er4u", to: "item-cleanup", label: "Item Master XLSX" },
  { from: "item-cleanup", to: "app-schema", label: "runs + decisions" },
  { from: "item-cleanup", to: "nextjs", label: "review queue" },
];
