"use client";
import { useCallback, useEffect, useMemo, useState } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Pagination } from "@/components/shared/Pagination";
import { itemCombinationCleanup } from "@/lib/api";
import type { ItemCombinationCleanupRow as Row, ItemCombinationCleanupRun as Run, ItemCombinationNameReview as NameReview, ItemCombinationNameReviewItem as NameReviewItem, ItemCombinationNameSuggestion as NameSuggestion } from "@/types/api";

type Queue = "all" | "packed-high" | "packed-medium" | "barcode" | "low" | "other";
type AiFilter = "all" | "LIKELY_PACKED_VERSION" | "LIKELY_EXTERNAL_OR_DIFFERENT_PRODUCT" | "UNCERTAIN" | "NOT_ASSESSED";
type NameMode = "deterministic" | "semantic" | "special" | "all";
type StaffReviewPreview = Awaited<ReturnType<typeof itemCombinationCleanup.previewStaffReviewImport>>;
const has = (r: Row) => Object.keys(r.proposed_changes).length > 0;
type WorkflowState = "SAFE" | "BATCH" | "REVIEW" | "UNCHANGED";
const workflowState = (r: Row): WorkflowState => {
 const c=r.proposed_changes;
 if(!Object.keys(c).length)return "UNCHANGED";
 if(r.review_status==="AUTO_APPROVED"&&r.product_type!=="PACKED"&&!c.brand&&(c.name||c.size))return "SAFE";
 if(r.approval_status==="PENDING"&&r.classification_confidence==="HIGH"&&(r.product_type==="PURCHASED"||r.product_type==="LOOSE")&&c.brand&&r.review_status==="AUTO_APPROVED")return "BATCH";
 return "REVIEW";
};
const queue = (r: Row): Queue => r.product_type === "PACKED" ? r.classification_confidence === "MEDIUM" ? "packed-medium" : "packed-high" : r.supplier_match_method === "barcode" ? "barcode" : r.classification_confidence === "LOW" ? "low" : "other";
const label: Record<Queue,string> = {all:"All decisions","packed-high":"PACKED · high","packed-medium":"PACKED · identity marker",barcode:"Supplier · barcode match only",low:"Low confidence",other:"Other ambiguous"};

export default function Page() {
 const [runs,setRuns]=useState<Run[]>([]),[run,setRun]=useState<Run|null>(null),[rows,setRows]=useState<Row[]>([]),[individualCompleted,setIndividualCompleted]=useState(0),[active,setActive]=useState<Queue>("all"),[aiFilter,setAiFilter]=useState<AiFilter>("all"),[page,setPage]=useState(0),[find,setFind]=useState(false),[q,setQ]=useState(""),[marked,setMarked]=useState<string[]>([]),[open,setOpen]=useState<string|null>(null),[busy,setBusy]=useState<string|null>(null),[notice,setNotice]=useState<string|null>(null),[staffImportOpen,setStaffImportOpen]=useState(false);
 const [nameReview,setNameReview]=useState<NameReview|null>(null),[nameMode,setNameMode]=useState<NameMode>("deterministic"),[nameRule,setNameRule]=useState("all");
 useEffect(()=>{itemCombinationCleanup.list().then(r=>{setRuns(r);setRun(r[0]??null);});},[]);
 const refreshRows=useCallback(async()=>{if(!run)return;const [first,names]=await Promise.all([itemCombinationCleanup.listRows(run.id,{limit:500,offset:0}),itemCombinationCleanup.listNameReview(run.id)]);const rest=await Promise.all(Array.from({length:Math.ceil(first.total/500)-1},(_,i)=>itemCombinationCleanup.listRows(run.id,{limit:500,offset:500*(i+1)})));setRows([...first.items,...rest.flatMap(x=>x.items)]);setIndividualCompleted(first.stats.individual_completed??0);setNameReview(names);},[run]);
 useEffect(()=>{let dead=false;refreshRows().catch(()=>{if(!dead)setNotice("Could not load this run.")});return()=>{dead=true};},[refreshRows]);
 const groups=useMemo(()=>({review:rows.filter(r=>workflowState(r)==="REVIEW"&&r.approval_status==="PENDING"),batch:rows.filter(r=>workflowState(r)==="BATCH"),safe:rows.filter(r=>workflowState(r)==="SAFE"),unchanged:rows.filter(r=>workflowState(r)==="UNCHANGED")}),[rows]);
 const aiMatches=(r:Row)=>aiFilter==="all"||aiFilter==="NOT_ASSESSED"?!r.semantic_assessment&&aiFilter==="NOT_ASSESSED"||aiFilter==="all":r.semantic_assessment?.relationship===aiFilter;
 const review=useMemo(()=>groups.review.filter(r=>active==="all"||queue(r)===active).filter(aiMatches).filter(r=>!q||[r.item_id,r.original_item_name,r.original_brand].join(" ").toLowerCase().includes(q.toLowerCase())),[groups,active,aiFilter,q]); const shown=review.slice(page*30,page*30+30);
 const filterCounts=useMemo(()=>Object.fromEntries((["packed-high","packed-medium","barcode","low","other"] as Queue[]).map(k=>[k,groups.review.filter(r=>queue(r)===k).length])) as Record<Queue,number>,[groups]);
 const aiCounts=useMemo(()=>Object.fromEntries((["LIKELY_PACKED_VERSION","LIKELY_EXTERNAL_OR_DIFFERENT_PRODUCT","UNCERTAIN","NOT_ASSESSED"] as AiFilter[]).map(k=>[k,groups.review.filter(r=>k==="NOT_ASSESSED"?!r.semantic_assessment:r.semantic_assessment?.relationship===k).length])) as Record<AiFilter,number>,[groups]);
 const nameItems=useMemo(()=>{const items=nameReview?.items??[];return items.filter(item=>nameMode==="all"||nameMode==="special"&&!!item.overlap_classification||nameMode==="deterministic"&&item.suggestions.some(s=>s.source==="NAMING_STANDARD")||nameMode==="semantic"&&item.suggestions.some(s=>s.source==="SEMANTIC_V2")).filter(item=>nameRule==="all"||item.suggestions.some(s=>s.safe_bulk_group===nameRule));},[nameReview,nameMode,nameRule]);
 const safeNameGroups=useMemo(()=>{const groups=new Map<string,string[]>();for(const item of nameReview?.items??[])for(const suggestion of item.suggestions)if(suggestion.safe_bulk_group)groups.set(suggestion.safe_bulk_group,[...(groups.get(suggestion.safe_bulk_group)??[]),suggestion.id]);return groups;},[nameReview]);
 label.all=`All decisions · ${groups.review.length}`; label["packed-high"]=`PACKED · high · ${filterCounts["packed-high"]}`; label["packed-medium"]=`PACKED · identity marker · ${filterCounts["packed-medium"]}`; label.barcode=`Supplier · barcode match only · ${filterCounts.barcode}`; label.low=`Low confidence · ${filterCounts.low}`; label.other=`Other ambiguous · ${filterCounts.other}`;
 const decide=async(ids:string[],status:"APPROVED"|"REJECTED")=>{if(!run||!ids.length)return;await itemCombinationCleanup.bulkDecision(run.id,{status,item_ids:ids});setRows(all=>all.map(r=>ids.includes(r.item_id)?{...r,approval_status:status}:r));setMarked([]);};
 const batch=async()=>{if(!run)return;setBusy("batch");try{const [purchased,loose]=await Promise.all([itemCombinationCleanup.bulkApprove(run.id,{type:"PURCHASED",confidence:"HIGH",status:"AUTO_APPROVED",brand_changed:true}),itemCombinationCleanup.bulkApprove(run.id,{type:"LOOSE",confidence:"HIGH",status:"AUTO_APPROVED",brand_changed:true})]);const updated=purchased.updated+loose.updated;setRows(all=>all.map(r=>workflowState(r)==="BATCH"?{...r,approval_status:"APPROVED"}:r));setNotice(`Accepted ${updated.toLocaleString()} high-confidence supplier updates.`);}finally{setBusy(null)}};
 useEffect(()=>{const handler=()=>batch();window.addEventListener("cleanup-batch-approve",handler);return()=>window.removeEventListener("cleanup-batch-approve",handler);},[run,rows]);
 const field=async(r:Row,name:string,decision:"ACCEPTED"|"REJECTED"|"EDITED"|"FINALIZE",edited_value?:string)=>{if(!run)return;if(decision==="FINALIZE"){const out=await itemCombinationCleanup.finalizeFieldDecisions(run.id,r.item_id);setRows(all=>all.map(x=>x.item_id===r.item_id?{...x,approval_status:out.approval_status}:x));setIndividualCompleted(count=>count+1);setNotice("Individual field decisions finalized. The row has left Individual Review.");return;}const out=await itemCombinationCleanup.decideField(run.id,r.item_id,name,{decision,edited_value});setRows(all=>all.map(x=>x.item_id===r.item_id?{...x,approval_status:out.approval_status,field_decisions:{...x.field_decisions,[name]:{decision:out.decision,edited_value:out.edited_value}}}:x));};
 const staff=async(ids:string[]=[],packed=false)=>{if(!run)return;const count=ids.length||review.length;if(!confirm(`Export ${count} review items for staff?\n\nThis workbook is for review only and cannot be uploaded directly to ER4U.`))return;setNotice("Staff-review workbook is being generated. It contains no ER4U export changes.");await itemCombinationCleanup.exportStaffReview(run.id,{item_ids:ids,packed_only:packed});};
 const exportFinal=async()=>{if(!run)return;if(!confirm("Generate the final ER4U-compatible Excel from all authoritative decisions?\n\nThe source workbook will not be overwritten and nothing will be imported into ER4U."))return;setBusy("final-export");setNotice("Final Excel is being generated and validated…");try{const exported=await itemCombinationCleanup.exportApproved(run.id);setRun(exported);setRuns(all=>all.map(candidate=>candidate.id===exported.id?exported:candidate));const filename=`${run.source_file_name.replace(/\.xlsx$/i,"")}_approved.xlsx`;await itemCombinationCleanup.downloadApproved(run.id,filename);setNotice(`Downloaded ${filename}.`);}catch(error){setNotice(error instanceof Error?error.message:"The final Excel could not be generated.");}finally{setBusy(null)}};
 const decideName=async(suggestion:NameSuggestion,decision:"ACCEPTED"|"REJECTED"|"EDITED",edited_value?:string)=>{if(!run)return;setBusy(suggestion.id);try{await itemCombinationCleanup.decideNameSuggestion(run.id,suggestion.id,{decision,edited_value});setNameReview(await itemCombinationCleanup.listNameReview(run.id));setNotice(decision==="REJECTED"?"Name suggestion rejected; the effective Name was unchanged.":"Name decision saved. Brand, Size, supplier, and PACKED state were not changed.");}finally{setBusy(null)}};
 const acceptNameBatch=async(rule:string,ids:string[])=>{if(!run||!ids.length)return;if(!confirm(`Accept ${ids.length} exact “${rule}” Name corrections?\n\nOnly the Name field will become authoritative. No semantic suggestions or other fields are included.`))return;setBusy(`batch:${rule}`);try{const result=await itemCombinationCleanup.bulkAcceptNameSuggestions(run.id,ids);setNameReview(await itemCombinationCleanup.listNameReview(run.id));setNotice(`Accepted ${result.updated} exact ${rule} Name corrections.`);}finally{setBusy(null)}};
 return <>
  <div className="mx-auto max-w-6xl space-y-5 p-6">
   <header className="flex flex-wrap items-end justify-between gap-3 border-b pb-4">
    <div><p className="text-xs font-semibold uppercase tracking-widest text-slate-500">ER4U item cleanup</p><h1 className="text-2xl font-semibold">Decision inbox</h1><p className="text-sm text-slate-600">Only operator decisions are shown by default.</p></div>
    <div className="flex flex-wrap gap-2"><Button variant="outline" onClick={()=>setFind(v=>!v)}>{find?"Close Find":"Find an item"}</Button><Button onClick={exportFinal} disabled={!run||busy==="final-export"}>{busy==="final-export"?"Generating final Excel…":"Export final Excel"}</Button><Button variant="outline" onClick={()=>staff()}>Export for staff review</Button><Button variant="outline" onClick={()=>setStaffImportOpen(true)}>Import staff review</Button></div>
   </header>
   {runs.length>0&&<select className="h-9 w-full rounded border px-2 text-sm" value={run?.id??""} onChange={e=>setRun(runs.find(x=>x.id===e.target.value)??null)}>{runs.map(r=><option key={r.id} value={r.id}>{r.source_file_name} · {r.row_count?.toLocaleString()} items</option>)}</select>}
    <section className="grid gap-3 md:grid-cols-2"><Summary title="Needs Individual Review" count={groups.review.length}/><Summary title="Ready for Batch Review" count={groups.batch.length}/><Summary title="Safe Mechanical Cleanup" count={groups.safe.length}/><Summary title="No Proposed Change" count={groups.unchanged.length}/></section>
    {nameReview&&<section className="rounded-xl border border-slate-200 bg-white p-4">
     <div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="font-semibold">Name corrections</h2><p className="text-xs text-slate-600">Phase 5 suggestions are advisory until you accept one. Stale baselines and resolved items are hidden.</p></div><div className="text-right"><p className="text-2xl font-semibold">{nameReview.stats.unique_items}</p><p className="text-xs text-slate-500">items awaiting Name review</p></div></div>
     <div className="mt-3 grid gap-2 sm:grid-cols-4"><NameMetric label="Deterministic only" count={nameReview.stats.deterministic_only_items}/><NameMetric label="Semantic only" count={nameReview.stats.semantic_only_items}/><NameMetric label="Overlap / conflict" count={nameReview.stats.overlap_items}/><NameMetric label="Stale excluded" count={nameReview.stats.stale_excluded}/></div>
     <div className="mt-3 flex flex-wrap gap-2">{(["deterministic","semantic","special","all"] as NameMode[]).map(mode=><button key={mode} className={`rounded-full border px-3 py-1 text-xs capitalize ${nameMode===mode?"border-blue-600 bg-blue-50":""}`} onClick={()=>{setNameMode(mode);setNameRule("all")}}>{mode}</button>)}</div>
     {safeNameGroups.size>0&&<div className="mt-3 rounded-lg border border-emerald-200 bg-emerald-50 p-3"><p className="text-xs font-semibold uppercase text-emerald-900">Verified exact-mapping batches</p><div className="mt-2 flex flex-wrap gap-2">{Array.from(safeNameGroups.entries()).map(([rule,ids])=><div key={rule} className="flex overflow-hidden rounded-md border border-emerald-300 bg-white"><button className="px-3 py-1.5 text-xs" onClick={()=>{setNameMode("deterministic");setNameRule(rule)}}>{rule} · {ids.length}</button><button className="border-l border-emerald-300 px-3 py-1.5 text-xs font-semibold text-emerald-800" disabled={busy===`batch:${rule}`} onClick={()=>acceptNameBatch(rule,ids)}>Accept batch</button></div>)}</div><p className="mt-2 text-xs text-emerald-800">Server validation rechecks the current baseline, exact single-rule output, human decisions, and semantic conflicts before applying.</p></div>}
     <div className="mt-3 space-y-2">{nameItems.map(item=><NameReviewCard key={item.item_id} item={item} busy={busy} decide={decideName}/>)}</div>
     {nameItems.length===0&&<p className="mt-4 rounded bg-slate-50 p-4 text-center text-sm text-slate-600">No pending Name items in this review group.</p>}
    </section>}
   <section className="rounded-xl border border-slate-200 bg-white p-4">
    <div className="mb-3 flex justify-between"><div><h2 className="font-semibold">Individual review</h2><p className="text-xs text-slate-600">Subqueues prioritize navigation; all evidence stays visible.</p><p className="mt-1 text-xs font-medium text-emerald-700">Individually completed: {individualCompleted}</p></div><span>{review.length} items</span></div>
    <div className="mb-3 flex flex-wrap gap-2">{(["all","packed-high","packed-medium","barcode","low","other"] as Queue[]).map(k=><button key={k} className={`rounded-full border px-3 py-1 text-xs ${active===k?"border-blue-600 bg-blue-50":""}`} onClick={()=>{setActive(k);setPage(0)}}>{label[k]}</button>)}</div>
    <label className="mb-3 flex items-center gap-2 text-xs font-medium text-slate-600">AI review <select className="h-8 rounded border bg-white px-2 text-sm" value={aiFilter} onChange={e=>{setAiFilter(e.target.value as AiFilter);setPage(0)}}><option value="all">All AI results · {groups.review.length}</option><option value="LIKELY_PACKED_VERSION">Likely packed by us · {aiCounts.LIKELY_PACKED_VERSION}</option><option value="LIKELY_EXTERNAL_OR_DIFFERENT_PRODUCT">Likely external / different product · {aiCounts.LIKELY_EXTERNAL_OR_DIFFERENT_PRODUCT}</option><option value="UNCERTAIN">Uncertain · {aiCounts.UNCERTAIN}</option><option value="NOT_ASSESSED">No AI assessment · {aiCounts.NOT_ASSESSED}</option></select></label>
    {marked.length>0&&<div className="mb-3 flex gap-2 rounded bg-blue-50 p-2"><span>{marked.length} selected</span><Button size="sm" onClick={()=>decide(marked,"APPROVED")}>Approve selected</Button><Button size="sm" variant="outline" onClick={()=>decide(marked,"REJECTED")}>Reject selected</Button><Button size="sm" variant="outline" onClick={()=>staff(marked)}>Export selected for staff review</Button></div>}
    <div className="mb-2 flex justify-end gap-2"><button className="rounded border px-2 py-1 text-xs" onClick={()=>setMarked(shown.map(r=>r.item_id))}>Select all visible</button><button className="rounded border px-2 py-1 text-xs" onClick={()=>setMarked(review.map(r=>r.item_id))}>Select all {review.length} in this subqueue</button></div>
    {find&&<Input className="mb-3" value={q} onChange={e=>setQ(e.target.value)} placeholder="Item_Id, name, or brand…"/>}
    <div className="space-y-2">{shown.map(r=><Card key={r.item_id} row={r} open={open===r.item_id} toggle={()=>setOpen(open===r.item_id?null:r.item_id)} marked={marked.includes(r.item_id)} select={()=>setMarked(a=>a.includes(r.item_id)?a.filter(i=>i!==r.item_id):[...a,r.item_id])} field={field} all={s=>decide([r.item_id],s)}/>)}</div>
    <Pagination page={page} setPage={setPage} totalPages={Math.max(1,Math.ceil(review.length/30))} total={review.length} pageSize={30}/>
   </section>
   {notice&&<p className="rounded border border-slate-200 bg-slate-50 p-3 text-sm text-slate-700">{notice}</p>}
  </div>
  {run&&<StaffImportDialog open={staffImportOpen} runId={run.id} onClose={()=>setStaffImportOpen(false)} onApplied={async message=>{await refreshRows();setNotice(message)}}/>}
 </>;
}

function StaffImportDialog({open,runId,onClose,onApplied}:{open:boolean;runId:string;onClose:()=>void;onApplied:(message:string)=>Promise<void>}){
 const [file,setFile]=useState<File|null>(null),[preview,setPreview]=useState<StaffReviewPreview|null>(null),[loading,setLoading]=useState(false),[applying,setApplying]=useState(false),[error,setError]=useState<string|null>(null),[result,setResult]=useState<{applied_rows:number;applied_fields:number;protected_rows:number;not_sure_rows:number}|null>(null);
 useEffect(()=>{if(open)return;setFile(null);setPreview(null);setError(null);setResult(null);setLoading(false);setApplying(false)},[open]);
 if(!open)return null;
 const inspect=async()=>{if(!file)return;setLoading(true);setError(null);setResult(null);try{setPreview(await itemCombinationCleanup.previewStaffReviewImport(runId,file))}catch(e){setPreview(null);setError(e instanceof Error?e.message:"The workbook could not be previewed.")}finally{setLoading(false)}};
 const apply=async()=>{if(!file||!preview)return;setApplying(true);setError(null);try{const applied=await itemCombinationCleanup.applyStaffReviewImport(runId,file,preview.file_hash);setResult(applied);setPreview(null);await onApplied(`Applied ${applied.applied_rows} staff-reviewed rows (${applied.applied_fields} field decisions). ${applied.protected_rows} previously resolved rows remained protected.`)}catch(e){setError(e instanceof Error?e.message:"The staff decisions could not be applied.")}finally{setApplying(false)}};
 const applicable=preview?.rows.filter(row=>row.eligibility==="APPLICABLE")??[];
 const protectedRows=preview?.rows.filter(row=>row.eligibility==="PROTECTED")??[];
 return <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/45 p-4" role="dialog" aria-modal="true" aria-labelledby="staff-import-title">
  <div className="flex max-h-[90vh] w-full max-w-4xl flex-col overflow-hidden rounded-xl border border-slate-200 bg-white shadow-2xl">
   <header className="flex items-start justify-between border-b border-slate-200 px-6 py-5">
    <div><p className="text-xs font-semibold uppercase tracking-widest text-blue-700">Staff review workbook</p><h2 id="staff-import-title" className="mt-1 text-xl font-semibold text-slate-950">Preview and apply decisions</h2><p className="mt-1 text-sm text-slate-600">Previewing never changes data. Decisions are written only after you press the final Apply button.</p></div>
    <button className="rounded-md px-3 py-1.5 text-sm text-slate-600 hover:bg-slate-100" onClick={onClose} disabled={applying}>Close</button>
   </header>
   <div className="overflow-y-auto px-6 py-5">
    {!result&&<section className="rounded-lg border border-slate-200 bg-slate-50 p-4">
     <label className="block text-sm font-medium text-slate-900" htmlFor="staff-workbook">Select the completed staff-review XLSX</label>
     <p className="mb-3 text-xs text-slate-600">Already resolved rows and existing field decisions are protected and cannot be overwritten.</p>
     <div className="flex flex-wrap items-center gap-3"><Input id="staff-workbook" type="file" accept=".xlsx" className="max-w-xl bg-white" onChange={e=>{setFile(e.target.files?.[0]??null);setPreview(null);setResult(null);setError(null)}}/><Button variant="outline" onClick={inspect} disabled={!file||loading||applying}>{loading?"Checking workbook…":"Preview workbook"}</Button></div>
     {file&&<p className="mt-2 text-xs text-slate-500">Selected: {file.name}</p>}
    </section>}
    {error&&<p className="mt-4 rounded-lg border border-rose-200 bg-rose-50 p-3 text-sm text-rose-800">{error}</p>}
    {result&&<section className="rounded-lg border border-emerald-200 bg-emerald-50 p-5">
     <h3 className="font-semibold text-emerald-950">Staff decisions applied</h3>
     <p className="mt-1 text-sm text-emerald-900">{result.applied_rows} rows and {result.applied_fields} field decisions were applied. {result.protected_rows} previously resolved rows were left unchanged.</p>
     <p className="mt-2 text-xs text-emerald-800">The Decision Inbox has refreshed automatically.</p>
    </section>}
    {preview&&<>
     <section className="mt-4 grid gap-3 sm:grid-cols-4">
      <ImportMetric label="Will apply" count={preview.summary.applicable} tone="blue"/>
      <ImportMetric label="Protected / skipped" count={preview.summary.protected} tone="slate"/>
      <ImportMetric label="Not sure / blank" count={preview.summary.not_sure} tone="slate"/>
      <ImportMetric label="Invalid" count={preview.summary.invalid} tone={preview.summary.invalid?"rose":"slate"}/>
     </section>
     <div className="mt-5 flex items-baseline justify-between"><div><h3 className="font-semibold text-slate-950">Validated actions</h3><p className="text-xs text-slate-600">These are the only fields that the import will change.</p></div><span className="text-sm font-medium text-slate-700">{applicable.reduce((sum,row)=>sum+row.actions.length,0)} field decisions</span></div>
     <div className="mt-3 max-h-72 space-y-2 overflow-y-auto rounded-lg border border-slate-200 p-2">
      {applicable.length===0?<p className="p-4 text-center text-sm text-slate-600">No new decisions are eligible to apply. This workbook may already have been imported.</p>:applicable.map(row=><article key={row.item_id} className="rounded-md border border-slate-200 bg-white p-3"><div className="flex justify-between gap-3"><p className="text-sm font-semibold text-slate-900">Item #{row.item_id}</p><span className="rounded-full bg-blue-50 px-2 py-0.5 text-xs font-medium text-blue-700">Staff: {row.staff_decision}</span></div><div className="mt-2 space-y-1">{row.actions.map(action=><p key={action.field} className="text-sm text-slate-700"><span className="font-medium capitalize">{action.field}</span>: <span className={action.action==="REJECT"?"text-rose-700":"text-emerald-700"}>{action.action}</span> · {action.from||"blank"} <span className="text-slate-400">→</span> {action.to||"blank"}{action.corrected&&<span className="ml-2 text-xs text-blue-700">staff-corrected value</span>}</p>)}</div></article>)}
     </div>
     {protectedRows.length>0&&<details className="mt-3 rounded-lg border border-slate-200 bg-slate-50 p-3"><summary className="cursor-pointer text-sm font-medium text-slate-700">Show {protectedRows.length} protected/skipped rows</summary><div className="mt-2 max-h-36 overflow-y-auto text-xs text-slate-600">{protectedRows.map(row=><p key={row.item_id}>Item #{row.item_id} — {row.reason??"Existing decision is protected"}</p>)}</div></details>}
    </>}
   </div>
   <footer className="flex items-center justify-between gap-3 border-t border-slate-200 bg-slate-50 px-6 py-4">
    <p className="text-xs text-slate-600">Applying is atomic: if the workbook or current decision state changed after preview, nothing is written.</p>
    <div className="flex shrink-0 gap-2"><Button variant="outline" onClick={onClose} disabled={applying}>{result?"Done":"Cancel"}</Button>{preview&&<Button onClick={apply} disabled={applying||preview.summary.applicable===0||preview.summary.invalid>0}>{applying?"Applying…":`Apply ${preview.summary.applicable} staff-reviewed rows`}</Button>}</div>
   </footer>
  </div>
 </div>
}

function ImportMetric({label,count,tone}:{label:string;count:number;tone:"blue"|"slate"|"rose"}){const colors=tone==="blue"?"border-blue-200 bg-blue-50 text-blue-900":tone==="rose"?"border-rose-200 bg-rose-50 text-rose-900":"border-slate-200 bg-slate-50 text-slate-900";return <div className={`rounded-lg border p-3 ${colors}`}><p className="text-xs font-medium">{label}</p><p className="mt-1 text-2xl font-semibold">{count}</p></div>}

function NameMetric({label,count}:{label:string,count:number}){return <div className="rounded-lg border bg-slate-50 p-3"><p className="text-xs text-slate-600">{label}</p><p className="text-xl font-semibold">{count}</p></div>}
function NameReviewCard({item,busy,decide}:{item:NameReviewItem,busy:string|null,decide:(s:NameSuggestion,d:"ACCEPTED"|"REJECTED"|"EDITED",v?:string)=>void}){return <article className={`rounded-lg border p-3 ${item.overlap_classification?"border-amber-300 bg-amber-50/40":""}`}><div className="flex flex-wrap items-start justify-between gap-2"><div><p className="font-medium">{item.effective_name}</p><p className="text-xs text-slate-500">Item #{item.item_id} · Current effective Name</p></div>{item.overlap_classification&&<span className="rounded-full bg-amber-100 px-2 py-1 text-xs font-semibold text-amber-900">{item.overlap_classification.replaceAll("_"," ")}</span>}</div><div className="mt-3 space-y-2">{item.suggestions.map(suggestion=><NameSuggestionPanel key={suggestion.id} suggestion={suggestion} busy={busy===suggestion.id} decide={(decision,value)=>decide(suggestion,decision,value)}/>)}</div></article>}
function NameSuggestionPanel({suggestion,busy,decide}:{suggestion:NameSuggestion,busy:boolean,decide:(d:"ACCEPTED"|"REJECTED"|"EDITED",v?:string)=>void}){const [editing,setEditing]=useState(false),[value,setValue]=useState(suggestion.suggested_value);const transformations=suggestion.transformations.map(change=>typeof change==="string"?change:`${change.original_text} → ${change.replacement_text}`);return <section className={`rounded-md border p-3 ${suggestion.source==="NAMING_STANDARD"?"border-emerald-200 bg-emerald-50":"border-blue-200 bg-blue-50"}`}><div className="flex flex-wrap items-center justify-between gap-2"><span className={`rounded-full px-2 py-0.5 text-[11px] font-semibold ${suggestion.source==="NAMING_STANDARD"?"bg-emerald-100 text-emerald-900":"bg-blue-100 text-blue-900"}`}>{suggestion.source==="NAMING_STANDARD"?"Deterministic naming standard":"Semantic advisory"}</span><span className="text-xs text-slate-600">{suggestion.version}{suggestion.confidence?` · ${suggestion.confidence} confidence`:""}</span></div><p className="mt-2 text-sm"><span className="text-slate-600">Proposed:</span> <span className="font-semibold">{suggestion.suggested_value}</span></p><p className="mt-1 text-xs font-medium text-slate-700">{transformations.join(", ")}</p>{suggestion.reason&&<p className="mt-2 text-sm text-slate-700">{suggestion.reason}</p>}{(suggestion.purchase_item_names.length>0||suggestion.catalog_siblings.length>0)&&<details className="mt-2 text-xs text-slate-700"><summary className="cursor-pointer font-medium">Purchase / catalog evidence</summary>{suggestion.purchase_item_names.length>0&&<p className="mt-1">Same-item purchases: {suggestion.purchase_item_names.join(" · ")}</p>}{suggestion.catalog_siblings.length>0&&<p className="mt-1">Catalog siblings: {suggestion.catalog_siblings.join(" · ")}</p>}</details>}{editing?<div className="mt-3 flex gap-2"><Input value={value} onChange={event=>setValue(event.target.value)}/><Button size="sm" disabled={busy||!value.trim()} onClick={()=>decide("EDITED",value)}>Accept edited</Button><Button size="sm" variant="outline" onClick={()=>setEditing(false)}>Cancel</Button></div>:<div className="mt-3 flex gap-2"><Button size="sm" disabled={busy} onClick={()=>decide("ACCEPTED")}>Accept</Button><Button size="sm" variant="outline" disabled={busy} onClick={()=>decide("REJECTED")}>Reject</Button><Button size="sm" variant="outline" disabled={busy} onClick={()=>setEditing(true)}>Edit</Button></div>}</section>}

function Summary({title,count}:{title:string,count:number}){const batch=title==="Ready for Batch Review";return <article className="rounded-xl border bg-slate-50 p-4"><p className="text-xs font-semibold uppercase text-slate-500">{title}</p><p className="text-3xl font-semibold">{count}</p>{batch&&<><p className="text-sm text-slate-600">High-confidence supplier updates</p><Button size="sm" className="mt-3" variant="outline" onClick={()=>window.dispatchEvent(new Event("cleanup-batch-approve"))}>Accept {count.toLocaleString()} supplier updates</Button></>}</article>}
function Card({row,open,toggle,marked,select,field,all}:{row:Row,open:boolean,toggle:()=>void,marked:boolean,select:()=>void,field:(r:Row,n:string,d:"ACCEPTED"|"REJECTED"|"EDITED"|"FINALIZE",v?:string)=>void,all:(s:"APPROVED"|"REJECTED")=>void}){const ai=row.semantic_assessment;const ready=Object.keys(row.proposed_changes).every(k=>["ACCEPTED","REJECTED"].includes(row.field_decisions[k]?.decision));return <article className="rounded-lg border p-3"><div className="flex justify-between gap-2"><div><p className="font-medium">{row.original_item_name}</p><p className="text-xs text-slate-500">Item #{row.item_id} · {row.product_type} · {row.classification_confidence}</p></div><div className="flex gap-2"><Button size="sm" variant="outline" onClick={select}>{marked?"Selected":"Select"}</Button><Button size="sm" variant="outline" onClick={toggle}>{open?"Hide evidence":"View evidence"}</Button>{ready?<Button size="sm" onClick={()=>field(row,"name","FINALIZE")}>Finalize individual decisions</Button>:<><Button size="sm" onClick={()=>all("APPROVED")}>Approve all changes</Button><Button size="sm" variant="outline" onClick={()=>all("REJECTED")}>Reject all changes</Button></>}</div></div><section className="mt-3 border-t pt-2"><p className="text-[11px] font-semibold uppercase text-slate-500">What would change</p>{Object.entries(row.proposed_changes).map(([name,v])=><Field key={name} name={name} original={v.original} proposed={v.proposed} state={row.field_decisions[name]} decide={(d,value)=>field(row,name,d,value)}/>)}</section>{ai&&<section className={`mt-3 rounded border p-3 ${row.semantic_disagrees_with_packed_proposal?"border-rose-300 bg-rose-50":"border-blue-200 bg-blue-50"}`}><p className="text-[11px] font-semibold uppercase">AI semantic check</p><p className="font-semibold">{ai.relationship==="LIKELY_PACKED_VERSION"?"Likely packed by us":ai.relationship==="LIKELY_EXTERNAL_OR_DIFFERENT_PRODUCT"?"Likely external / different product":"Uncertain"}</p><p className="text-sm">{ai.confidence} confidence · {ai.reason}</p>{row.semantic_disagrees_with_packed_proposal&&<p className="mt-1 font-semibold text-rose-800">⚠ AI disagrees with Brand → PKG.</p>}</section>}<section className="mt-3 border-t pt-2 text-sm"><p className="text-[11px] font-semibold uppercase text-slate-500">Why AxonFlux proposed it</p><p>Matched LOOSE product: {String((row.classification_evidence as Record<string,unknown>)?.source_loose_item_name??"not available")}</p></section>{open&&<details open className="mt-2 rounded bg-slate-50 p-2 text-xs"><summary>Advanced · Raw evidence</summary><pre>{JSON.stringify(row.classification_evidence,null,2)}</pre></details>}</article>}
function Field({name,original,proposed,state,decide}:{name:string,original:string|null,proposed:string|null,state?:{decision:string,edited_value:string|null},decide:(d:"ACCEPTED"|"REJECTED"|"EDITED"|"FINALIZE",v?:string)=>void}){const [edit,setEdit]=useState(false),[value,setValue]=useState(state?.edited_value??proposed??"");return <div className="mt-2 rounded border p-2 text-sm"><p className="capitalize font-medium">{name}</p><p>{original||"Not available"} <span className="text-slate-400">→</span> {proposed||"blank"}</p>{state?.decision==="ACCEPTED"?<p className="text-green-700">✓ Accepted — will be exported</p>:state?.decision==="REJECTED"?<p className="text-slate-600">✕ Rejected — original value will be kept</p>:state?.decision==="EDITED"?<p className="text-amber-700">Edited — not yet approved: {state.edited_value}</p>:null}{edit?<div className="mt-1 flex gap-2"><Input value={value} onChange={e=>setValue(e.target.value)}/><Button size="sm" onClick={()=>{decide("EDITED",value);setEdit(false)}}>Save edit</Button><Button size="sm" variant="outline" onClick={()=>setEdit(false)}>Cancel</Button></div>:<div className="mt-1 flex gap-2"><Button size="sm" variant="outline" onClick={()=>decide("ACCEPTED")}>{state?.decision==="EDITED"?"Accept edited value":"Accept"}</Button><Button size="sm" variant="outline" onClick={()=>decide("REJECTED")}>Reject</Button><Button size="sm" variant="outline" onClick={()=>setEdit(true)}>Edit</Button></div>}</div>}
